<?php
$inlineJs = false;
if(isset($_GET['js-inline'])) {
    $inlineJs = true;
}
?>
<!-- core js -->
<?php 
if($this->removeAdobeJSJunk()) {
    if(!$inlineJs) {
        if($this->isMinifyEnabled(true)) {
            $fileName = $block->getViewFileUrl('React_React::js/react-core.min.js');
        } else {
            $fileName = $block->getViewFileUrl('React_React::js/react-core.js');
        }
        ?>
        <script defer src="<?php echo $fileName; ?>"></script>
        <?php
    } else {
        echo $this->getInlineJs('react-core.js');
    }
}
?>
<!-- inline js -->
