<?php
$isProductPage = $this->registry->registry('current_product') ? true : false;
$criticalCSSHTML = boolval($this->config->getValue('react_vue_config/css/critical'));

if ($criticalCSSHTML || isset($_GET['css-html'])) {
    $criticalCSSHTML = true;
}
if ($isProductPage && $criticalCSSHTML) {
    $css = @file_get_contents(BP . '/pub/static/product-critical-m.css');
    ?>
<style media="screen and (max-width: 768px)">
<?=$css?>
</style>
<?php
}?>
<script>
<?php
$product = $this->registry->registry('current_product');
$request = $this->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();
$fullAction = $request->getFullActionName();
$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$uenc = base64_encode($currentUrl);

if ($product) {?>
window.productType = "<?=$product->getTypeId();?>";
<?php }?>
window.curentUenc = "<?=$uenc?>";
window.controller = "<?=$controller?>";
window.action = "<?=$action?>";
window.fullAction = "<?=$fullAction?>";
</script>


<?php 
if($this->removeAdobeJSJunk()) {
?>
<script>
if (typeof require !== "function") {
    window.require = function (modules, callback) {
    console.warn("We are not using RequireJS anymore");
};
}
if (typeof require.config === "undefined") {
    require.config = function () {};
}
</script>
<?php
}
?>

<!--
<script defer="defer" src="<?=$block->getViewFileUrl('React_React::js/cash.js');?>"> </script>
-->