<!-- CSS Header Start -->
<style>
@media (min-width: 768px) {
    .nav-toggle {
        display: none !important;
    }
    .block-search input {
        margin: 0 !important;
        padding-right: 35px !important;
        position: static !important;
    }
    .header.panel>.header.links {
        display: block;
        margin: 0 !important;
        padding: 0 !important;
        list-style: none none !important;
        float: right !important;
        margin-left: auto !important;
    }
    form.minisearch .control  {
        border-top: 0 !important;
    }
    .page-header {
        border: 0 !important;
        margin-bottom: 0 !important;
    }

    .header.content {
        padding: 30px 20px 0 !important;
    }

    .block-search .action.search:before {
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 16px;
        line-height: 32px;
        color: #757575;
        content: '\e615';
        font-family: 'luma-icons';
        margin: 0;
        vertical-align: top;
        display: inline-block;
        font-weight: normal;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
    .block-search .action.search {
        display: block !important;
    }
    .minicart-wrapper,.block.block-search{
        margin-top:10px;
    }
    .logo {
            margin: -8px auto 25px 0 !important;
    }
}
</style>
<style>
    <?=
    // View files must be added to inline php or compiled every time 
    "@font-face {
        font-family: 'luma-icons';
        src: url('" . $block->getViewFileUrl('fonts/Luma-Icons.woff2') . "') format('woff2'),
             url('" . $block->getViewFileUrl('fonts/Luma-Icons.woff') . "') format('woff');
        font-weight: 400;
        font-style: normal;
        font-display: block;
    }";
    ?>

body,html {
    height: 100%
}

.message.global.demo .content{
    max-height: 42px !important;
}

.header.content {
    max-height: 96px;
}

.swatch-attribute.size .swatch-option {
    color: black;
}
.message.global.demo {
    color: black;
}
.product-options-wrapper{
    min-height: 134px;
}
.product-info-main .product-info-stock-sku {
    display: inline-block;
    float: right;
    padding-bottom: 10px;
    padding-left: 10%;
    text-align: right;
    vertical-align: top;
}
/* Desck */
@media only screen and (min-width: 768px) {
    form.minisearch .control {
        display: block;
    }
    .product.info.detailed{
        clear: both;
    }
}
/* Mobile */
@media only screen and (max-width: 768px) {
    form.minisearch .control {
        display: none;
    }
    .swatch-attribute.size .swatch-option {
        color: black !important;
    }
    .product-info-main {
        margin-top: 25px;
    }
    .message.global.demo {
        color: black !important;
    }
    input#search {
        position: unset !important;
    }
}

block.related .product-item-details {
    margin-top: 25px !important;
}

.product-item-name {
    margin: 10px 0;
}
a.product-item-link {
    font-size: 16px;
}

.swatch-option.text.selected {
    box-shadow: 0 0 10px 4px #007bff;
    border: 2px solid rgba(255, 215, 0, 1);
    transition: box-shadow 0.3s ease-in-out, border 0.3s ease-in-out;
}

.swatch-option.color.selected {
    box-shadow: 0 0 10px 4px #cbff00;
    border: 2px solid rgba(255, 215, 0, 1);
    transition: box-shadow 0.3s ease-in-out, border 0.3s ease-in-out;
}

.form-create-account .action.submit.primary, a.action.create.primary{
    display: none;
}

.products.wrapper.products-grid  input.swatch-input.super-attribute-select {
    display: none;
}

.products.wrapper.products-grid  .swatch-attribute-label {
    display: none;
}
</style>
<!-- CSS Header End -->
