<?php
$inlineJs = false;
?>
<!-- core js -->
<?php 
if($this->removeAdobeJSJunk()) {
    if(!$inlineJs) {
?>
<script defer src="<?php echo $block->getViewFileUrl('React_React::js/react-core.js'); ?>"></script>
<?php
    } else {
        echo getInlineJs();
    }
}

function getInlineJs() {
    $jsContent = file_get_contents(__DIR__ . '/js/react-core.js');
    return '<script>' . $jsContent . '</script>';
}
?>
<!-- inline js -->
